DATABASE_URL = "postgresql://postgres.inywjvokefyhajbhyxla:pyhfit-pipMik-4qumfa@aws-1-us-east-1.pooler.supabase.com:5432/postgres"
CENSUS_API_KEY = "46b0b716ec0d0352c315c28c8ec8933ca4e86a5c"
DEEPSEEK_API_KEY = "sk-062a771079854d168a9d554fc5901953"